title: Khalisha Zafira
email: khalishazhafira76@gmail.com
descreption: Mahasiswa Politeknik Negeri Lhokseumawe Jurusan TIK Prodi Teknik Informatika 
url: 'https://khalisha0zafira.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag