title: Khalisha Zafira
email: khalishazhafira76@gmail.com
descreption: Journey Anak Informatika
url: 'https://khalisha0zafira.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag