title: Khalisha Zafira
email: khalishazhafira76@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Journey Anak Informatika
url: 'https://khalisha0zafira.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag