title: Khalisha Zafira
email: khalishazhafira76@gmail.com
descreption: 
   Hai, aku khalisha zafira seorang mahasiswi dari Politeknik Negeri Lhokseumawe. Selain kuliah, aku suka banget baca buku 
   dan eksperimen dengan resep masakan baru di dapur. Dua hal itu bikin aku merasa lebih tenang dan bisa fokus kembali setelah banyak kegiatan.
   Aku percaya kalau belajar itu nggak cuma dari buku atau pelajaran di kampus, tapi juga dari pengalaman sehari-hari. Saat ini, 
   aku lagi menikmati perjalanan kuliah dan terus berusaha menjadi pribadi yang lebih baik, nggak hanya di akademik tapi juga di kehidupan sehari-hari.

url: 'https://khalisha0zafira.github.io'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag